services:
    register_user_handler:
        class: User\Command\RegisterUserHandler
        arguments:
            - @doctrine
            - @mailer
        tags:
            - {name: command_handler, handles: \User\Command\RegisterUser }
