services:
    register_user_handler:
        class: User\Command\RegisterUserHandler
        arguments:
            - @doctrine
        tags:
            - {name: command_handler, handles: \User\Command\RegisterUser }



    when_user_was_registered_send_welcome_email:
        class: User\Event\WhenUserWasRegisteredSendWelcomEmail
        arguments:
            - @mailer
        tags:
            - { name: event_subscriber, subscribes_to: User\Event\UserWasRegistered }



    register_user_console_command:
        class: User\Cli\RegisterUserConsoleCommand
        calls:
            - [setContainer, [@service_container]]
        tags:
            - { name: console.command }