services:
    register_user_handler:
        class: User\Command\RegisterUserHandler
        arguments:
            - @user_repository
        tags:
            - {name: command_handler, handles: User\Command\RegisterUser }


    update_user_handler:
        class: User\Command\UpdateUserHandler
        arguments:
            - @user_repository
        tags:
            - {name: command_handler, handles: User\Command\UpdateUser }



    when_user_was_registered_send_welcome_email:
        class: User\Event\WhenUserWasRegisteredSendWelcomEmail
        arguments:
            - @mailer
        tags:
            - { name: event_subscriber, subscribes_to: User\Event\UserWasRegistered }



    register_user_console_command:
        class: User\Cli\RegisterUserConsoleCommand
        calls:
            - [setContainer, [@service_container]]
        tags:
            - { name: console.command }


    user_repository:
        class: User\Persistence\DoctrineUserRepository
        arguments:
            - @doctrine

